# This is a basic workflow to help you get started with Actions

name: gitee mirror

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  to_gitee:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:umeng/mp-demos.git
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
